DROP TABLE IF EXISTS conf;
CREATE TABLE conf (
    key VARCHAR(64) PRIMARY KEY NOT NULL,
    value VARCHAR(256)
);

DROP TABLE IF EXISTS document;
CREATE TABLE document (
    id CHAR(8) PRIMARY KEY NOT NULL,
    path VARCHAR(128) UNIQUE NOT NULL,
    name VARCHAR(128) NOT NULL,
    tags VARCHAR(256) NOT NULL
);
